### ISSUE TITLE
【feat】frequency/period support reverse mode

### ISSUE THREAD

**Issue by begoat** [c6p/logseq-habit-tracker#12]
For some habits, I want them "at most" `frequency/period`.
We can add one button to mark whether it's a Forward / Reverse habit.

For example, I have a habit called #eat-too-much. I will only track it when i really eat too much. I set the frequency/period to at most 3 days one month. add this feature is useful for me~

**Comment by c6p** [comment]
Thanks. Wonderful idea. I'll add them in the next version.
