### ISSUE TITLE
Support for task as TODO

### ISSUE THREAD

**Issue by Xemnas0** [c6p/logseq-habit-tracker#15]
It would be useful to be able to parse a habit block as a TODO block. Blocks with "DONE" get counted in the habit tracker

**Comment by c6p** [comment]
Currently, it can be implemented by modifying patterns. I'll think about making them default in future versions. In the meantime:
```json
{
  "habitPattern": "^(TODO|DONE)?\\s*?(?<habit>.*?)(?:| - (?<count>.*?))$",
  "ignorePattern": "TODO.*"
}
```
Note: `\` is escaped in `\\s`, if you are modifying settings within UI, replace with `\s`.
