### ISSUE TITLE
Question about coloring behavior in UI

### ISSUE THREAD

**Issue by mstine** [c6p/logseq-habit-tracker#19]
Hi there,

I've dug a bit through existing issues and the source code, but I'm not finding the answer to my question very easily, so I thought I'd just ask.

I started using the plugin yesterday, and I've noticed some behavior that seems odd to me but is likely intended.

Here's a habit block:

```
- ## Habits  
	- DONE Meditate for 5 Minutes #[[Area: 🧠🧘🏻‍♂️Mental Health]] #habit  
	- LATER Complete a Workout #[[Area: Health]] #habit  
	- DONE Read Daily Stoic #[[Area: Character Development]] #habit  
	- LATER Publish an Atomic Essay #[[Area: Writing]] #habit  
```

![image](https://user-images.githubusercontent.com/11889/184906417-25dfe5f9-af81-4377-ab14-eec59c74edcf.png)

Notice that the habits I've checked off for today (8-16) are colored red and do not contain a number, while the habits I checked off for yesterday do contain a number, and the `1/d` habits are colored green.

I take this to mean that you don't apply the final coloring/numbering to a cell until the full 24-hour day has elapsed. Is this correct?

If so, this was surprising behavior to me. I would have expected any habit which has met it's frequency/period goal to immediately be colored green (producing the subsequent "dopamine hit" from accomplishing a goal).

Thoughts?

Thanks again for a marvelous plugin!

**Comment by c6p** [comment]
Thanks, @mstine, for compliments.

I cannot exactly reproduce it.  Could you share your configuration and habit blocks for both today and yesterday?

Numbering and colouring should be immediate, though I think sometimes Logseq returns stale results to queries, if after checking any habit, numbers are not reflected, you may refresh or re-index.

Not 24-hour day, but habits are checked and coloured using a rolling window period. So for any given day if the frequency in the last n-days (7 days for a [w]eek including that day) is greater than or equal to the target, it is green, else red.

So within your first period, the day will be coloured in red until the target 5 has been surpassed within a week. In my opinion, it is the correct behaviour, though I'm open to suggestions.

Cheers

**Comment by mstine** [comment]
Sure! The below is after I reindexed a couple of times to ensure nothing was awry with my graph.

Your logic seems sound for the numbering and coloring, but it doesn't appear to work in my case.

Thanks again.

## Config

```json
{
  "disabled": false,
  "colors": [],
  "dateFormat": "MM-DD",
  "habits": {
    "Read Daily Stoic #[[Area: Character Development]]": {
      "period": "1/d",
      "order": 1
    },
    "Complete a Workout #[[Area: Health]]": {
      "period": "5/w",
      "order": 2
    },
    "Meditate for 5 Minutes #[[Area: 🧠🧘🏻‍♂️Mental Health]]": {
      "period": "1/d",
      "order": 0
    },
    "Publish an Atomic Essay #[[Area: Writing]]": {
      "period": "5/w",
      "order": 3
    },
    "Brand new habit #[[Area: Finances]]": {
      "period": "1/d"
    }
  },
  "habitPattern": "^(LATER|DONE)?\\s*(?<habit>.*?)(?:| - (?:(?<int>\\d*?) times|(?<count>.*?)))$",
  "ignorePattern": "LATER .*",
  "hideStreak": false
}
```

## Yesterday (August 15)

```markdown
- ## Habits  
	- DONE Meditate for 5 Minutes #[[Area: 🧠🧘🏻‍♂️Mental Health]] #habit  
	- DONE Complete a Workout #[[Area: Health]] #habit  
	- DONE Read Daily Stoic #[[Area: Character Development]] #habit  
	- DONE Publish an Atomic Essay #[[Area: Writing]] #habit  
```

## Today (August 16)

```markdown
- ## Habits  
	- DONE Meditate for 5 Minutes #[[Area: 🧠🧘🏻‍♂️Mental Health]] #habit  
	- DONE Complete a Workout #[[Area: Health]] #habit  
	- DONE Read Daily Stoic #[[Area: Character Development]] #habit  
	- DONE Publish an Atomic Essay #[[Area: Writing]] #habit  
```

## Latest Screenshot

![image](https://user-images.githubusercontent.com/11889/184990997-3f09ba8b-ac1a-4baf-b8fd-bb119b9a0d69.png)

**Comment by mstine** [comment]
Update just to show how things are progressing.

## Today (August 17)

```markdown
- ### Habits  
	- DONE Meditate for 5 Minutes #[[Area: 🧠🧘🏻‍♂️Mental Health]] #habit  
	- DONE Complete a Workout #[[Area: Health]] #habit  
	- DONE Read Daily Stoic #[[Area: Character Development]] #habit  
	- LATER Publish an Atomic Essay #[[Area: Writing]] #habit  
```

## Latest Screenshot

![image](https://user-images.githubusercontent.com/11889/185210963-8c08e085-2b4d-4e36-8f6a-f32bbabb7827.png)

**Comment by c6p** [comment]
Sorry for the late answer. I can't reproduce it. Is Logseq and the plugin updated to the latest version?

![image](https://user-images.githubusercontent.com/80478/185444311-8a182b99-98d6-4933-98c7-4a6e06f375f1.png)

Did you re-index the graph? Could you try with a clean directory?

**Comment by mstine** [comment]
My apologies for the annoyance... when I checked for updates previously, nothing happened (network hiccup I guess), so I had assumed I was up to date. Apparently, I wasn't.

Updating to 0.8.1 fixed the problem (even without a reindex).

**Comment by c6p** [comment]
No problem. Happy to see your problem has been resolved.

Cheers.

**Comment by mstine** [comment]
Reopening this because the behavior keeps coming back (off and on), and I'm really not sure what to do.

I studied your source code to extract the query, and everything *looks fine* to me, but I haven't studied the coloring code enough to know what's happening to cause this:

![image](https://user-images.githubusercontent.com/11889/185969526-742e941b-ded3-4145-add0-61f4dbafa683.png)

The oddities here:

- The two habits I checked off for today have gone back to the behavior where they are colored red with no number.
- The habit (Complete a Workout) where I completed 5 days in a 7 day period (meeting the frequency/period goal) is red until the habit is completed on 8-19, and then green going forward until today where there is no color. 
- Also, for that same habit, there's a streak of 3? I do not understand that at all.

Let me know what data I can provide to help. Over the weekend, I did a lot of cleaning out of old cruft from when I moved from Obsidian to Logseq which I thought could corrupt the graph. I also disconnected, deleted the `logseq` folder, and reconnected. This *briefly* made things better, but then the confusing behavior returned within minutes.

**Comment by c6p** [comment]
Thank you for reopening.

While investigating, I've found a presentational bug, when there are `< 14` days of habits, numbers and coloring are off in slice. I'm not sure whether your issue is triggered by this, but I think so.

Though, streak of 3 is curious. It should be 1. It seems to be a similar slicing error for the same edge case in success handling. 

If I cannot solve it as quick as I want (tomorrow?), the release should have to wait next week.

Cheers

**Comment by mstine** [comment]
Apologies for the delayed response.

Since last commenting, I've continued tracking habits:

At present, even after reindexing the graph, the UI seems to be stuck in a strange state:

![image](https://user-images.githubusercontent.com/11889/188139319-05a22765-0e2b-4cac-8bec-df59e280d1eb.png)

All habit tracking appears to stop on August 28th, even though I have continued tracking through today, September 2. (NOTE: I have changed my marker to `#[[ATOMIC HABIT ⚛️]]`, but that has worked as expected).

If I go back to August 1 and add habits:

![image](https://user-images.githubusercontent.com/11889/188139771-82307e9d-9ccc-4dec-b61f-fb8c45b84fbd.png)

The view gets very interesting indeed:

![image](https://user-images.githubusercontent.com/11889/188139901-78c1c29a-5e62-47b9-9e47-a7d3a9386879.png)
![image](https://user-images.githubusercontent.com/11889/188139957-ec68166a-8bab-4140-a9a6-1eb4ac792ebe.png)

**Comment by c6p** [comment]
Curious.

Sorry, I couldn't find time. I'll be away on my honeymoon for a few weeks.

**Comment by mstine** [comment]
Hi there - I hope you had a nice honeymoon! I was wondering if you're going to find time to look at this one soon. If not, no worries. Just checking in. Thanks!

**Comment by c6p** [comment]
Thanks for reaching out and best wishes, @mstine. Sorry for late answer. I'm currently occupied with other things. I will try to find some time to look all the issues.
