### ISSUE TITLE
Reports of Habits and complete visualization beyond 14 days

### ISSUE THREAD

**Issue by santiyounger** [c6p/logseq-habit-tracker#2]
Hey! thanks for the awesome plugin. I've been trying to achieve something like this in Logseq for a while, so I'm really happy to have a nice way to visualize my habits.

I'd love to know if there's any way to see beyond the current 2 weeks display
![image](https://user-images.githubusercontent.com/51902730/137151501-dfe5d4f8-7131-4499-9f68-c1565956cd59.png)
Like shown in the readme screenshot, there are 14 days at any given time.

Would it be possible to have a way to navigate beyond the 14 day limits into the past? or to have ways to know how many days has a habit been done

Or for daily habits, how long have I've kept a perfect streak without missing a day.

Being able to visualize this data or perhaps export it so that it can be visualized in a .csv spreadsheet would be incredible.

Thanks a lot, really appreciate the hard work you've put into this!

**Comment by santiyounger** [comment]
Hey, I just realized that making 2 requests on the same issue was a bad idea, sorry 🙃
considering that now it's possible to go back beyond the previous 14 limits that part of the issue could be considered done.

The aspect of exporting to .csv I think it's pretty important and probably others might like to contribute to it, however since I put it in this same issue it might be hard to find the request for .csv

with that said, let me know if you'd like me to create a new issue for .csv so that you can close this one. or feel free of course to organize things as you prefer and feel free to tag me. 

Thank you, love this plugin and I really hope .csv export becomes possible, since that's the only missing piece I have to move my habit tracker to this plugin

thank you!

**Comment by c6p** [comment]
Sorry for the delay.

Separate issues may have been better. Though, there is no need for it anymore. I think I can implement CSV export within a day. Stay tuned. 😉

**Comment by c6p** [comment]
@santiyounger check out v0.3.1. If there is any problem, please let me know.

**Comment by santiyounger** [comment]
hey thanks a lot for this, seems like I lost track of this notification! I just gave it a quick try! incredible work! thanks a lot for working on this

Have a great day!
