### ISSUE TITLE
Where is the gear icon?

### ISSUE THREAD

**Issue by dismory** [c6p/logseq-habit-tracker#21]
Maybe there is something wrong with my config, but I cannot find the gear icon and the habit tracking grid view.

**Comment by c6p** [comment]
Is there any error? Could you send a screenshot? Did you check the extensions overflow menu, does it list a show-habits entry?

**Comment by dismory** [comment]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/142608/194757883-9936068f-b941-4ab6-bfad-cdd941f8f054.png">

As the the document says that `Click on gear (⚙️) icon to edit settings.`, where could I find the gear icon?

**Comment by dismory** [comment]
Finally I find that it is toggled by the plugin icon.
