### ISSUE TITLE
Habits window cut out/incomplete?

### ISSUE THREAD

**Issue by iuliandita** [c6p/logseq-habit-tracker#22]
Hi there. Trying to get this plugin to work, but this is how it shows:

![image](https://user-images.githubusercontent.com/4585657/209311874-7d06050f-25c7-495d-ab5e-36a808b70bf0.png)

Am I missing something?
Also, how can I make it ignore the leading `####` (used for formatting)?

**Comment by cjbarroso** [comment]
I have the same issue, with the current last beta release, it happened with the previous one also. I disabled all other plugins and changed different themes to no avail.

**Comment by cjbarroso** [comment]
Are you using the `Tabs` plugin? Try disabling it, it worked for me

**Comment by c6p** [comment]
I cannot reproduce the issue on Logseq 8.14 with default theme, even with logseq-plugins-tabs v1.18.1.

Could you please try with a clean profile, and report back here?

As your second question, you can set habit pattern to: `^(#*\s)?(TODO|DONE)?\s*?(?<habit>.*?)(?:| - (?:(?<int>\d*?) times|(?<count>.*?)))$`

Cheers

**Comment by iuliandita** [comment]
@cjbarroso I disabled the Tabs plugin, and it works like it should now. Thanks for the tip! Any workaround so I can use both plugins?
@c6p that worked! thank you!
