### ISSUE TITLE
Using [[Habits]] as a linked parent block

### ISSUE THREAD

**Issue by santiyounger** [c6p/logseq-habit-tracker#3]
Hey, 
In order to make it quicker to create the daily block "Habits" I wanted to make it a linked block like this:
![image](https://user-images.githubusercontent.com/51902730/137153233-69237176-2ef6-4ad7-a366-5dfad3fe2aa8.png)

However, If I modify this in the plugin settings like this:
![image](https://user-images.githubusercontent.com/51902730/137153418-3708173f-fdef-4a72-9b52-3b626603b779.png)

it doesn't' work, plus it also send's the plugin window to the further left, unable to access the settings 

![image](https://user-images.githubusercontent.com/51902730/137153592-91bbeeba-86ad-4514-89bb-ee4d7673e723.png)

The only way to reset it to normal is by accessing the `logseq-habit-tracker.json` file manually from a text editor and reset it to default.

This is slightly different to #1 since with the solution I'm proposing we'd still be keeping the current parent block. 
However if the method from #1 is implemented, then that might replace the need to what I'm saying in this issue. Either way I think both methods would be beneficial for different types of users 

Thanks a lot for the hard work, this is soon becoming my favorite logseq plugin!

**Comment by c6p** [comment]
Thank you for the appreciation.

Could you try `#Habits` for now? I am going to fix linked blocks.

Also, could you update to the latest version, if you are not already? I cannot reproduce plugin moving further left, hiding settings, though I will look into it.

**Comment by santiyounger** [comment]
thanks! 
Regarding the moving plugin it's really strange. I'll see if there might be another factor that makes it happen, because I can confirm I'm on the version 0.1.5 of the plugin and of Logseq 0.4.3

Regarding the suggestion to use #habits would this be correct?

Feel free to let me know if you have suggestions, such as Upper case "H" for habits, or if Lower case "h" is better.
![image](https://user-images.githubusercontent.com/51902730/137350101-f6fe6b78-d10d-4d29-ae4e-fd681cd0ca31.png)

Thanks!

**Comment by c6p** [comment]
@santiyounger Oops, please try v0.2.1

**Comment by santiyounger** [comment]
thank you that seems to have solved it appreciate it!

**Comment by donkikos** [comment]
@c6p I tried using this regex `((\*{2}\d{2}:\d{2}\*{2})|(\d{2}:\d{2})|())(?<habit>.*((#habit)|(\[{2}habit\]{2}))(\s|\b))` so that I can label the blocks with either `#habit` or `[[habit]]`. It works for `#habit`, e.g. `09:14 meditation #habit
`, but does not recognize the `[[habit]]`, e.g. `09:14 meditation [[habit]]`.

**Comment by c6p** [comment]
@donkikos currently habit marker accepts a single form (and it is not regex capable). Let's make it a seperate issue.
