### ISSUE TITLE
Make box turn green as soon as habits are completed for curent day

### ISSUE THREAD

**Issue by steubens** [c6p/logseq-habit-tracker#4]
Hi, **I wonder if you can make today's habit box turn green once all your habits are completed for the desired frequency?**  As you see here, I have completed my 2/d pushups, but today still shows red in the tracker :( 
It would be awesome if that box could turn green as soon as I have completed my habits for the day, instead of having to wait for tomorrow to see it green... ya know?
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/6864307/138376360-60c68770-f5ef-43da-a0e1-f0da5cc7135b.png">

**Comment by c6p** [comment]
It should be green, I remember it painting correctly to green. I should have messed up something in last commits.

**Comment by mikob** [comment]
I'm having the opposite issue, where habits are marked green for today before I finish them:
![image](https://user-images.githubusercontent.com/492864/178109223-b08218b8-ae65-45ff-ba5b-c03d805c40d2.png)

**Comment by c6p** [comment]
@mikob sorry, I may have missed your comment. If the behaviour continues could you open a bug report and paste yor settings?

**Comment by mikob** [comment]
@c6p thanks for getting back to me. I've created the issue here: https://github.com/c6p/logseq-habit-tracker/issues/20
