### ISSUE TITLE
Enhancement: Ability to Reorder Habits

### ISSUE THREAD

**Issue by someinternetguy** [c6p/logseq-habit-tracker#5]
Just like the title says, a cool and helpful enhancement would be the ability to somehow reorder your habits as needed. 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/6864307/138755536-b436ebc5-eedc-420c-ac0f-b736f81aa9dd.png">
For instance, I would like to move Morning and Evening routines to the beginning and end of the list to make it more orderly to look at on a daily basis, etc.

**Comment by c6p** [comment]
Check out v0.3.2.

**Comment by someinternetguy** [comment]
@c6p, WOW, thank you! Love being able to reorder the habits, as well as have color groups, that's a cool feature! One thing new I noticed is the addition of streaks calculations... can we possibly get an option (check box) to hide that?  One of the reasons I use your tracker instead of say the "streaks" app on iPhone, is because I DO NOT like the pressure of the streaks being shown, but I DO want to track my habits to see that I am at least mostly consistent with them :) - let me know if you want me to make another enhancement post for this ask.  Thanks again for all your hard work, I use this plugin all day every day and really appreciate it!!!

**Comment by c6p** [comment]
Thanks, in the next version, I will add a show/hide streak checkbox. Cheers.
