### ISSUE TITLE
Enhancement: Keyboard shortcut to open and close habit tracker UI

### ISSUE THREAD

**Issue by steubens** [c6p/logseq-habit-tracker#6]
I find myself tracking a lot of habits as I go through my day using this awesome plugin!  That said, it's annoying to have to click it open and closed constantly to check what has been done and what needs to be completed.  It would be super handy to have a keyboard shortcut to open and close the UI, so one doesn't have to constantly reach for the mouse.

**Comment by someinternetguy** [comment]
With the newer versions of LogSeq, it looks like a keyboard shortcut to open and close the Tracker UI should be achievable.

**Comment by c6p** [comment]
Hey, thanks for letting me know. I'm getting some errors with the latest version of plugin API, it seems it is not the only change.

I hope, in a few days time, this feature will be implemented.
